### ISSUE TITLE
[ISSUE] Optimization

### ISSUE THREAD

**Issue by Rahuletto** [Rahuletto/AcademiaPro#14]
### Optimization sucks
Didn't expect enormous amount of traffic into the website, Resulting into hitting the limits of Vercel to bump into paid service which as we are open-source software, we can't really afford it.

![image](https://github.com/Rahuletto/AcademiaPro/assets/71836991/6c987847-cd88-45db-9955-4cc1c46e105d)
![image](https://github.com/Rahuletto/AcademiaPro/assets/71836991/b105140a-41ed-4308-b81b-ce3c700586bd)

This is `SEVERE`!!!
It might shut all of our services down. This includes `better-lab`, `academia-pro` and various softwares i host.

## TODO:
- [x] React Contexts
- [x] Usage of localStorage to offload
- [x] Better client caching of data
- [x] Offloading `proscrape` into maybe different account
